# Pares para 'rice-theme toggle' (oscuro <-> claro)
tokyonight=tokyonight-day
tokyonight-day=tokyonight
catppuccin-mocha=catppuccin-latte
catppuccin-latte=catppuccin-mocha
rose-pine=catppuccin-latte
gruvbox-dark=catppuccin-latte
