[General]
count=3
rules=rice-pip,rice-juegos,rice-android

[rice-pip]
Description=Picture-in-Picture siempre encima
above=true
aboveuserrule=3
skippager=true
skippagerrule=3
skiptaskbar=true
skiptaskbarrule=3
title=Picture-in-Picture
titlematch=1
noborder=true
noborderrule=3

[rice-juegos]
Description=Juegos de Steam al escritorio 4
desktops=rice-desktop-4
desktopsrule=3
noborder=true
noborderrule=3
wmclass=^steam_app_.*$
wmclasscomplete=false
wmclassmatch=3

[rice-android]
Description=Emulador de Android al escritorio 4
desktops=rice-desktop-4
desktopsrule=3
wmclass=^([Ee]mulator|qemu-system.*)$
wmclasscomplete=false
wmclassmatch=3
